#!/bin/bash

cd

# update
apt-get update
apt-get -y upgrade
apt-get -y install build-essential

# install
wget https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.28-9669-beta/softether-vpnserver-v4.28-9669-beta-2018.09.11-linux-x64-64bit.tar.gz
tar xzvf softether-vpnserver-v4.28-9669-beta-2018.09.11-linux-x64-64bit.tar.gz
cd vpnserver
#Installing server files, Manual input
clear
echo  -e "\033[31;7mNOTE: ANSWER 1 AND ENTER THREE TIMES FOR THE COMPILATION TO PROCEED\033[0m"
make
cd ..
mv vpnserver /usr/local
cd /usr/local/vpnserver/
chmod 600 *
chmod 700 vpnserver
chmod 700 vpncmd
wget -O /etc/init.d/vpnserver "https://raw.githubusercontent.com/dmynares/dm/master/softether.conf"
mkdir /var/lock/subsys
chmod 755 /etc/init.d/vpnserver
update-rc.d vpnserver defaults
/etc/init.d/vpnserver start
cd /usr/local/vpnserver
SE_PASSWORD=""
SE_PASSWORD=${SE_PASSWORD}
read -s -p "Set SE Server password: " SE_PASSWORD
echo ""
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /CMD ServerPasswordSet  ${SE_PASSWORD}
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /CMD HubCreate vpn /PASSWORD:vpn
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /HUB:vpn /CMD UserCreate vpn /GROUP:none /REALNAME:none /NOTE:none
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /HUB:vpn /CMD UserPasswordSet vpn /PASSWORD:vpn
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /CMD IPsecEnable /L2TP:yes /L2TPRAW:yes /ETHERIP:yes /PSK:vpn /DEFAULTHUB:vpn
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /CMD HubDelete DEFAULT
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /HUB:vpn /CMD SecureNatEnable
/usr/local/vpnserver/vpncmd localhost:5555 /SERVER /PASSWORD:vpn /CMD VpnOverIcmpDnsEnable /ICMP:yes /DNS:yes
echo ---------------------------------------------
echo  -e "\033[32;5mVPN SERVER INSTALLED SUCCESSFULLY!\033[0m"
echo "vpncmd is at /usr/local/vpnserver"
echo ---------------Commands----------------------
echo /etc/init.d/vpnserver start - to start
echo /etc/init.d/vpnserver restart - to restart
echo /etc/init.d/vpnserver stop - to stop
echo ---------------------------------------------
#End of script
