#!/bin/bash
# UsnekxPHC
clear
echo "                                                                 "
echo "                                                                 "
echo " _|    _|    _|_|_|  _|      _|  _|_|_|_|  _|    _|  _|      _|  "
echo " _|    _|  _|        _|_|    _|  _|        _|  _|      _|  _|    "
echo " _|    _|    _|_|    _|  _|  _|  _|_|_|    _|_|          _|      "
echo " _|    _|        _|  _|    _|_|  _|        _|  _|      _|  _|    "
echo "   _|_|    _|_|_|    _|      _|  _|_|_|_|  _|    _|  _|      _|  "
echo "                                                                 "
echo "                        AUTO SCRIPT                              "
echo "                                                                 "
echo " "

HOST=""
HOST=${HOST}
echo -n "Enter Server IP: "
read HOST
echo "Now sit back and wait until the installation finished."
echo " "

sudo apt-get -y update && sudo apt-get -y upgrade && apt-get install expect -y
sudo apt-get install checkinstall build-essential -y
wget http://www.softether-download.com/files/softether/v4.27-9666-beta-2018.04.21-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.27-9666-beta-2018.04.21-linux-x64-64bit.tar.gz
tar -xzf softether-vpnserver-v4.27-9666-beta-2018.04.21-linux-x64-64bit.tar.gz
rm -rf softether-vpnserver-v4.27-9666-beta-2018.04.21-linux-x64-64bit.tar.gz
cd /root/vpnserver && expect -c 'spawn make; expect number:; send 1\r; expect number:; send 1\r; expect number:; send 1\r; interact'
cd && mv vpnserver/ /usr/local && chmod 600 * /usr/local/vpnserver/ && chmod 700 /usr/local/vpnserver/vpncmd && chmod 700 /usr/local/vpnserver/vpnserver
echo '#!/bin/sh
# description: SoftEther VPN Server
### BEGIN INIT INFO
# Provides:          vpnserver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: softether vpnserver
# Description:       softether vpnserver daemon
### END INIT INFO
DAEMON=/usr/local/vpnserver/vpnserver
LOCK=/var/lock/subsys/vpnserver
test -x $DAEMON || exit 0
case "$1" in
start)
$DAEMON start
touch $LOCK
;;
stop)
$DAEMON stop
rm $LOCK
;;
restart)
$DAEMON stop
sleep 3
$DAEMON start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit 0' > /etc/init.d/vpnserver
###
chmod 755 /etc/init.d/vpnserver && /etc/init.d/vpnserver start
update-rc.d vpnserver defaults
###
echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=1
sysctl --system
echo "nameserver 8.8.8.8" > "/etc/resolv.conf"
echo "nameserver 8.8.4.4" >> "/etc/resolv.conf"

### SSH brute-force protection ### 
iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -m recent --set 
iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 10 -j DROP  
### Protection against port scanning ### 
iptables -N port-scanning 
iptables -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN 
iptables -A port-scanning -j DROP

HOST=${HOST}

TARGET="/usr/local/"

sleep 2
${TARGET}vpnserver/vpncmd localhost /SERVER /CMD ServerPasswordSet qq1122ww
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD HubCreate dmVPN /PASSWORD:1111
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /HUB:dmVPN /CMD UserCreate qqqq /GROUP:none /REALNAME:none /NOTE:none
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /HUB:dmVPN /CMD UserPasswordSet qqqq /PASSWORD:1111
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD IPsecEnable /L2TP:yes /L2TPRAW:yes /ETHERIP:no /PSK:vpn /DEFAULTHUB:dmVPN
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD HubDelete DEFAULT
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /HUB:dmVPN /CMD SecureNatEnable
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD VpnOverIcmpDnsEnable /ICMP:yes /DNS:yes
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 53
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 137
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 500
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 921
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 4500
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 4000
${TARGET}vpnserver/vpncmd localhost /SERVER /PASSWORD:qq1122ww /CMD ListenerCreate 40000
clear
echo "Softether server configuration has been done!"
echo " "
echo "Host: ${HOST}"
echo "Virtual Hub: dmVPN"
echo "Port: 443, 53, 137"
echo "Username: qqqq"
echo "Password: 1111"
echo "Server Password: qq1122ww"
echo " "
echo "Join us in TD's Discord Server"
echo "Invitation link: https://discord.gg/2BCNNYg"