#!/bin/bash

MYIP=$(curl -4 icanhazip.com)
if [ $MYIP = "" ]; then
   MYIP=`ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1`;
fi
MYIP2="s/xxxxxxxxx/$MYIP/g";

cd

#update
apt-get update
apt-get -y upgrade

#install
apt-get -y install nano
apt-get -y install build-essential
apt-get -y install nload

#ssh
sed -i 's/#Banner/Banner/g' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
wget -O /etc/issue.net "https://raw.githubusercontent.com/dmynares/dm/master/banner"

#squid
apt-get -y install squid3
wget -O /etc/squid/squid.conf "https://raw.githubusercontent.com/dmynares/dm/master/squid.conf"
sed -i $MYIP2 /etc/squid/squid.conf

#adduser
sudo adduser username --gecos ",,," --disabled-password
echo "username:password" | sudo chpasswd
usermod -s /bin/false username

#restart services
service ssh restart
service squid restart

clear
rm -f ubuntu
history -c

#reboot
echo "Server IP : $MYIP"
echo "SSH Port : 22"
echo "Squid Proxy : 8080"
echo "You need to [reboot] your server to complete this setup."
